Initial commit
aws/aws-sdk-php pull request #2135
Opened 2020-11-02 20:32 UTC by SamRemis

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-02 23:04 UTC, howardlopez requested changes

2020-11-02 23:04 UTC, howardlopez commented on tests/Credentials/CredentialProviderTest.php
> +    public function testCreatesFromProcessCredentialWithSharedFilename()
You've covered calling the providers directly, but should there also be a test that the default provider ends up using the new ENV variable as well?

2020-11-02 23:04 UTC, howardlopez commented on src/Credentials/CredentialProvider.php
>      /**
Nitpick: there should be a line break between const declarations and this doc block.

2020-11-03 19:37 UTC, howardlopez approved these changes

2020-11-16 21:10 UTC, mullermp approved these changes

2020-11-17 20:30 UTC, merged