testing
aws/aws-sdk-php pull request #2288
Opened 2021-08-11 20:21 UTC by vudh1

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-11 20:21 UTC, SamRemis requested changes

2021-08-11 20:21 UTC, SamRemis commented on src/functions.php
> +}
missing newline character here

2021-08-12 13:00 UTC, SamRemis approved these changes

2023-11-16 22:45 UTC, stobrien89 commented
Closing this now- we've implemented a generic resolver for configuration values.

2023-11-16 22:45 UTC, closed without merging