class name resolution
aws/aws-sdk-php pull request #2499
Opened 2022-07-21 13:07 UTC by amberovsky

*Description of changes:*
Use ::class for class name resolution 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-21 19:33 UTC, stobrien89 approved these changes

2023-03-21 19:34 UTC, stobrien89 commented
Thanks for the contribution, @amberovsky!

2023-03-28 16:38 UTC, stobrien89 requested changes
@amberovsky,

Thanks for all of the work on this.  I just had a few things we'd like to change.  Otherwise, very appreciative of the effort— helps us to be a bit more consistent and idiomatic.

2023-03-28 17:00 UTC, amberovsky commented on src/ClientResolver.php
> -                . 'Aws\Credentials\CredentialsInterface, an associative '
🤦

2023-03-28 17:05 UTC, amberovsky commented on src/ClientResolver.php
> -                . 'Aws\Credentials\CredentialsInterface, an associative '
Will fix it, I think it should be put in the backlog to write a test on this code block

2023-06-01 19:13 UTC, stobrien89 approved these changes

2023-06-01 19:15 UTC, stobrien89 commented
Thanks for the contribution @amberovsky! And apologies for the delay in getting back to this.

2023-06-01 19:15 UTC, merged