Alternative credential retrieval - threadsafe
aws/aws-sdk-php pull request #2722
Opened 2023-07-04 10:52 UTC by paullallier

Similar to PR 2155

*Description of changes: Fallback to $_SERVER variable for AWS credentials to avoid using non-threadsafe putenv()*

Would you consider allowing this change so that we can avoid having to use the non-threadsafe putenv() function to set AWS credentials - which were storing in a .env file?

I've tried to write a test for it - not sure it's going to work yet.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-04 12:58 UTC, paullallier commented
Found a minor problem. This doesn't seem to fall through to null when `$_SERVER[self::ENV_SESSION]` is undefined.  I'm tempted to remove that one since I don't need it, but maybe there's a better way?
`getenv(self::ENV_SESSION) ?: $_SERVER[self::ENV_SESSION] ?: NULL`

2023-09-05 14:17 UTC, arnaubuch commented
Could we get this merged eventually? Thanks!

2024-01-31 09:33 UTC, paullallier commented
Any chance of a review and comments on how we could make this an acceptable merge, please?

2024-07-01 19:42 UTC, stobrien89 requested changes

2024-07-01 19:42 UTC, stobrien89 commented on src/Credentials/CredentialProvider.php
> +            $key = getenv(self::ENV_KEY) ?: $_SERVER[self::ENV_KEY];
The `$_SERVER` references should check to see if it is set.  Also, we should fall back to false if it isn't. I think you could add a null coalescing operator to what's already here and add `false` on the right side of the operand.

2024-07-12 23:35 UTC, paullallier commented
I'm not sure why I thought @server would set the $_SERVER variable for the test. Fixed this, but is there a cleaner option? 

Sorry - I should have run the tests locally (which I have now down with PHP 8.3 at least).

2025-08-31 20:03 UTC, paullallier commented
Sorry. I'd love to get this into a mergeable state, but getting it to pass the tests on all the test suites appears to be beyond my skill level. :-(

2025-09-02 23:02 UTC, stobrien89 commented
Hi @paullallier,

Apologies for the delay.  We'll get these fixed up and get the PR merged as soon as possible.

2026-07-27 17:28 UTC, stobrien89 commented
Hey @paullallier,

Sorry for the very delayed response.  I was reviewing this today and I don't think this is something we can merge.  There are too many tests that depend on credential 'emptiness' and there's not a great way for us to set these values and restore them when running unit tests. Something we'll keep in mind if we end up overhauling our credential providers though.  Thanks again for the PR!

2026-07-27 17:28 UTC, closed without merging