Add "after" callback for the Transfer class
aws/aws-sdk-php pull request #2723
Opened 2023-07-09 19:53 UTC by Mastertrap21

*Description of changes:*
Added possibility to execute a callback function after a transfer is fulfilled when using the Transfer class. Implemented similarly to the way the 'before' callback works.

While using the transfer class, particularly the upload methods, I could see that there is a "before" callback I can use but there is no "after" callback. I needed such an "after" callback to cleanup the files as they are getting uploaded. Because of this I have implemented an "after" callback similar to the "before" callback which uses the fulfill callback option. It now can be used as follows:

```php
$s3Client->uploadDirectory($path, $bucket, null, [
    'after' => function(\Aws\Result $result, int $index, \GuzzleHttp\Promise\Promise $aggregatePromise) {
        // Do something with $result or check $aggregatePromise
    }
]);
```

I think such a feature might be helpful to others in the future as well. I have created this PR to see if you also agree having an "after" callback would be a good idea and the code is just a fast copy paste from the "before" callback. If there is agreement that this would be a good idea, I can/will write some more tests and proper documentation about this new callback.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-11 20:44 UTC, stobrien89 commented
Hi @Mastertrap21,

I think we'd be open to accepting something like this.  Seems like a perfectly reasonable way to do this and I'd imagine others may like the option to perform a task after transfer operation.  

We generally like to have a feature request (in the form of an issue) open before we decide to merge a community requested feature, so if you could do that (feel free to copy over some of the description from this PR and link it as well), it'd be greatly appreciated.  Some people pay more attention to issues on our repository and we like to give others the chance upvote or chime in about these sorts of things.

2023-07-11 21:42 UTC, Mastertrap21 commented
Hi @stobrien89, 

Thank you for your quick response, openness and guidance regarding this feature, it's always nice to contribute to a well maintained project.

I have now opened a feature request in the form of an issue here: https://github.com/aws/aws-sdk-php/issues/2725
I will write some specific tests for the new callback tomorrow when I get some extra time.
I'm not sure about the existing checks, I can see that it is failing because of the added nextrelease changelog JSON. Is that something I should look into?

2024-09-30 20:13 UTC, stobrien89 requested changes
@madalindk,  

LGTM, just need to move that changelog entry file to `.changes/nextrelease/`. from the SDK base directory.  Looks like it ended up in some old build artifacts.

2025-03-18 17:56 UTC, stobrien89 approved these changes

2025-03-18 18:06 UTC, merged