chore: added workflow for handling answerable discussions
aws/aws-sdk-php pull request #2728
Opened 2023-07-14 20:22 UTC by khushail

*Issue #, if available:*

*Description of changes:*

This workflow will handle the discussions (posted in answerable category) and take appropriate action.

Whenever a discussion is replied with keyword @github-actions proposed-answer, is considered for action by this workflow and based on the responses/reactions received, appropriate action is taken.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-17 17:27 UTC, stobrien89 approved these changes

2023-07-18 12:33 UTC, GrahamCampbell requested changes

2023-07-19 22:00 UTC, khushail commented on .github/workflows/handle-stale-discussions.yml
> +          GITHUB_TOKEN:  ${{secrets.GITHUB_TOKEN}}
incorporated suggested changes

2023-07-20 00:00 UTC, GrahamCampbell requested changes

2023-07-20 00:00 UTC, GrahamCampbell commented on .github/workflows/handle-stale-discussions.yml
> +
too many newlines at end of file. we went from 0 to 2. there should be 1

2023-08-08 17:17 UTC, merged